
version: '2'

services:
    # acceleration:
    #     image: chalmersfsd/acceleration:oscar-latest
    #     network_mode: "host"
    #     command: "cfsd18-cognition-acceleration --surfaceId=211 --cid=253\
    #     --cidWheelSpeed=219 --speedId1=1504 --speedId2=1505 --id=317 --verbose=1 --gatheringTimeMs=50 --separationTimeMs=10 --Kp=0.0349 --Ki=0 --targetSpeed=10 --accLimit=6"

    vehicle-view:
        image: chrberger/opendlv-vehicle-view-amd64:20180720
        # restart: on-failure
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        ports:
        - "8081:8081"

    cfsd18-sim-visualization:
        image: chalmersfsd/cfsd18-sim-visualization:pre-release-778bfb6
        network_mode: "host"
        ports:
        - "8000:8000"
        command: "--cid=253"

    recorder48:
        image: chrberger/cluon-amd64:latest
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/recordings
        working_dir: "/opt/recordings"
        command: sh -c "cluon-OD4toStdout --cid=253 > `date +CID-48-recording-%Y-%m-%d_%H%M%S.rec`"
